# Copyright (c) FootPrints Labs Team.

# Use this file to set default values for configuration variables 
# specified in jupyter configuration file.  
# Using the yaml module, the configs will be substitute by these configuration variables.

# Fargate spawner AWS Configs
FARGATESPAWNER_AWS_REGION: us-east-1
FARGATESPAWNER_AWS_ECS_HOST: ec2-54-91-93-88.compute-1.amazonaws.com


# Custer name in which the tasks will be running
CLUSTER_NAME: test-jupyter

# The task definition for running in the cluster
CLUSTER_TASK_DEFINITION: test-jupyter:19

# Network configuration for the Fargate and aws vpc Configurations
# NOTE: Can have multiple Security Groups and Subnets in the list
ASSIGN_PUBLIC_IP: ENABLED
SECURITY_GROUPS: 
  - sg-0be79785ab8369203
SUBNETS: 
  - subnet-8e560fc3
PLATFORM_VERSION: 1.4.0

# Logo File Name that will be assigned to the JupyterHub Dashboard Logo
LOGO_FILE_NAME: logo.png

## The ip or hostname for proxies and spawners to use for connecting to the Hub.
# Instance/ECS IP address where the Docker container is running.
# Keep the private IP address
HUB_CONNECT_IP: 172.31.21.81

# Max users that can use the server
MAX_NUMBER_OF_USERS: 10

# DATABSE CONFIGS
RDS_SQL_DB_USERNAME: admin
RDS_SQL_DB_PASSWORD: footprint
RDS_SQL_DB_ENDPOINT: footprint.cufclga4hs85.us-east-1.rds.amazonaws.com
RDS_SQL_DB_PORT: 3306
RDS_SQL_DB_NAME: jupyterhub_test

# Proxy server configs
# Private IP of the machine
# Don't chnage the port. It should be 8001
HTTP_PROXY_API_URL : http://172.31.81.192:8001
HTTP_PROXY_AUTH_TOKEN : eyJhY2NvdW50SWQiOjI0Mjk1LCJ1c2VyVHlwZSI6ImFkbWluIiwiZW1haWwiOiJzYWJpaGF0QGtvY